version: '3.8'
services:
  nginx:
    image: nginx:1.21
    ports:
      - 8081:8081
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
    depends_on:
      - php
      - nuxt

  php:
    build: ./docker/php
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - nuxt

  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 24678:24678
      - 3002:3000
    volumes:
      - ./nuxt:/var/www/html
    working_dir: /var/www/html
    command: npm run dev

  mysqlredcomm:
    image: mysql/mysql-server:8.0
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: demo
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: