version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8081:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/public:/var/www/html/public
    depends_on:
      - php
      - nuxt

  php:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - nuxt

  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 24678:24678
      - 3002:3000
    volumes:
      - ./nuxt:/var/www/html
    working_dir: /var/www/html
    command: npm run dev